# TCL File Generated by Component Editor 21.1
# Wed May 14 11:51:17 EDT 2025
# DO NOT MODIFY


# 
# camera_interface "CAMERA_INTERFACE" v1.0
#  2025.05.14.11:51:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module camera_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CAMERA_INTERFACE
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "vga_ball"
set_module_assignment embeddedsw.dts.group "vga"


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file camera_interface.sv SYSTEM_VERILOG PATH camera_interface.sv TOP_LEVEL_FILE
add_fileset_file debounce_better_version.sv SYSTEM_VERILOG PATH debounce_better_version.sv
add_fileset_file flipflip.sv SYSTEM_VERILOG PATH flipflip.sv
add_fileset_file my_dff_en.sv SYSTEM_VERILOG PATH my_dff_en.sv
add_fileset_file clock_enable.sv SYSTEM_VERILOG PATH clock_enable.sv


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group c_mod_input
set_module_assignment embeddedsw.dts.name camera
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink pclk clk Input 1


# 
# connection point camera_data
# 
add_interface camera_data conduit end
set_interface_property camera_data associatedClock clock_sink
set_interface_property camera_data associatedReset reset
set_interface_property camera_data ENABLED true
set_interface_property camera_data EXPORT_OF ""
set_interface_property camera_data PORT_NAME_MAP ""
set_interface_property camera_data CMSIS_SVD_VARIABLES ""
set_interface_property camera_data SVD_ADDRESS_GROUP ""

add_interface_port camera_data href href Input 1
add_interface_port camera_data vsync vsync Input 1
add_interface_port camera_data d d Input 8
add_interface_port camera_data shutter_raw shutter_raw Input 1


# 
# connection point camera_interface_fifo_ST
# 
add_interface camera_interface_fifo_ST avalon_streaming start
set_interface_property camera_interface_fifo_ST associatedClock clock_sink
set_interface_property camera_interface_fifo_ST associatedReset reset
set_interface_property camera_interface_fifo_ST dataBitsPerSymbol 8
set_interface_property camera_interface_fifo_ST errorDescriptor ""
set_interface_property camera_interface_fifo_ST firstSymbolInHighOrderBits true
set_interface_property camera_interface_fifo_ST maxChannel 0
set_interface_property camera_interface_fifo_ST readyLatency 0
set_interface_property camera_interface_fifo_ST ENABLED true
set_interface_property camera_interface_fifo_ST EXPORT_OF ""
set_interface_property camera_interface_fifo_ST PORT_NAME_MAP ""
set_interface_property camera_interface_fifo_ST CMSIS_SVD_VARIABLES ""
set_interface_property camera_interface_fifo_ST SVD_ADDRESS_GROUP ""

add_interface_port camera_interface_fifo_ST fifo_enable valid Output 1
add_interface_port camera_interface_fifo_ST wide_bit_out data Output 32

