# TCL File Generated by Component Editor 21.1
# Wed May 14 12:18:16 EDT 2025
# DO NOT MODIFY


# 
# camera_clk "CAMERA_CLK" v1.0
#  2025.05.14.12:18:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module camera_clk
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_clk
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CAMERA_CLK
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera_clk
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file camera_clk.sv SYSTEM_VERILOG PATH camera_clk.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group camera_clk
set_module_assignment embeddedsw.dts.name camera_clk
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock_input
# 
add_interface clock_input clock end
set_interface_property clock_input clockRate 0
set_interface_property clock_input ENABLED true
set_interface_property clock_input EXPORT_OF ""
set_interface_property clock_input PORT_NAME_MAP ""
set_interface_property clock_input CMSIS_SVD_VARIABLES ""
set_interface_property clock_input SVD_ADDRESS_GROUP ""

add_interface_port clock_input clk clk Input 1


# 
# connection point pclk_io
# 
add_interface pclk_io clock end
set_interface_property pclk_io clockRate 0
set_interface_property pclk_io ENABLED true
set_interface_property pclk_io EXPORT_OF ""
set_interface_property pclk_io PORT_NAME_MAP ""
set_interface_property pclk_io CMSIS_SVD_VARIABLES ""
set_interface_property pclk_io SVD_ADDRESS_GROUP ""

add_interface_port pclk_io cam_pclk clk Input 1


# 
# connection point pclk_fpga
# 
add_interface pclk_fpga clock start
set_interface_property pclk_fpga associatedDirectClock ""
set_interface_property pclk_fpga clockRate 0
set_interface_property pclk_fpga clockRateKnown false
set_interface_property pclk_fpga ENABLED true
set_interface_property pclk_fpga EXPORT_OF ""
set_interface_property pclk_fpga PORT_NAME_MAP ""
set_interface_property pclk_fpga CMSIS_SVD_VARIABLES ""
set_interface_property pclk_fpga SVD_ADDRESS_GROUP ""

add_interface_port pclk_fpga fpga_pclk clk Output 1


# 
# connection point xclk_io
# 
add_interface xclk_io clock start
set_interface_property xclk_io associatedDirectClock ""
set_interface_property xclk_io clockRate 0
set_interface_property xclk_io clockRateKnown false
set_interface_property xclk_io ENABLED true
set_interface_property xclk_io EXPORT_OF ""
set_interface_property xclk_io PORT_NAME_MAP ""
set_interface_property xclk_io CMSIS_SVD_VARIABLES ""
set_interface_property xclk_io SVD_ADDRESS_GROUP ""

add_interface_port xclk_io cam_xclk clk Output 1

