# TCL File Generated by Component Editor 21.1
# Wed May 14 09:47:44 EDT 2025
# DO NOT MODIFY


# 
# camera_io "CAMERA_IO" v1.0
#  2025.05.14.09:47:44
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module camera_io
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_io
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME CAMERA_IO
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera_io
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file camera_io.sv SYSTEM_VERILOG PATH camera_io.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point camera_io
# 
add_interface camera_io conduit end
set_interface_property camera_io associatedClock clk_fake
set_interface_property camera_io associatedReset reset_fake
set_interface_property camera_io ENABLED true
set_interface_property camera_io EXPORT_OF ""
set_interface_property camera_io PORT_NAME_MAP ""
set_interface_property camera_io CMSIS_SVD_VARIABLES ""
set_interface_property camera_io SVD_ADDRESS_GROUP ""

add_interface_port camera_io cam_data cam_data Input 8
add_interface_port camera_io cam_href cam_href Input 1
add_interface_port camera_io cam_vsync cam_vsync Input 1
add_interface_port camera_io switch_shutter switch_shutter Input 1


# 
# connection point camera_data
# 
add_interface camera_data conduit end
set_interface_property camera_data associatedClock clk_fake
set_interface_property camera_data associatedReset reset_fake
set_interface_property camera_data ENABLED true
set_interface_property camera_data EXPORT_OF ""
set_interface_property camera_data PORT_NAME_MAP ""
set_interface_property camera_data CMSIS_SVD_VARIABLES ""
set_interface_property camera_data SVD_ADDRESS_GROUP ""

add_interface_port camera_data d d Output 8
add_interface_port camera_data href href Output 1
add_interface_port camera_data shutter_raw shutter_raw Output 1
add_interface_port camera_data vsync vsync Output 1


# 
# connection point reset_fake
# 
add_interface reset_fake reset end
set_interface_property reset_fake associatedClock clk_fake
set_interface_property reset_fake synchronousEdges DEASSERT
set_interface_property reset_fake ENABLED true
set_interface_property reset_fake EXPORT_OF ""
set_interface_property reset_fake PORT_NAME_MAP ""
set_interface_property reset_fake CMSIS_SVD_VARIABLES ""
set_interface_property reset_fake SVD_ADDRESS_GROUP ""

add_interface_port reset_fake reset reset Input 1


# 
# connection point clk_fake
# 
add_interface clk_fake clock end
set_interface_property clk_fake clockRate 0
set_interface_property clk_fake ENABLED true
set_interface_property clk_fake EXPORT_OF ""
set_interface_property clk_fake PORT_NAME_MAP ""
set_interface_property clk_fake CMSIS_SVD_VARIABLES ""
set_interface_property clk_fake SVD_ADDRESS_GROUP ""

add_interface_port clk_fake clk clk Input 1

